### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xillwillx** [UltimateLabs/Zoom#4]
[+] api.w.org seems to use WordPress
Traceback (most recent call last):
  File "zoom.py", line 144, in <module>
    automatic(url, domain)
  File "zoom.py", line 105, in automatic
    version_vul(version[0], version[1])
  File "zoom.py", line 52, in version_vul
    if not jsoned[version_dec]['vulnerabilities']:
KeyError: u'5.0-alpha-43170'

**Comment by UltimateHackers** [comment]
Hi there,
Zoom assumes that the version is a decimal number while the target you are trying to attack seems to run a version which doesn't follow this schema.
This is not a bug tbh as you won't find it running on the normal websites as well as on the wpvuldb.
But I will see what I can do.
Thanks for reporting.
